name: Release

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Prepare Maven release
        run: |
          ./mvnw --batch-mode release:prepare
          RELEASE_VERSION=$(grep -r 'scm.tag=' release.properties | sed 's/scm.tag=//')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
