name: Release - Prepare

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'pom.xml version to prepare (eg: 1.2.3 [without v!!!])'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Prepare Maven release
        run: |
          ./mvnw --batch-mode release:prepare -DreleaseVersion=${{ github.event.inputs.release_version }}
          RELEASE_TAG=$(grep -r 'scm.tag=' release.properties | sed 's/scm.tag=//')
          echo "RELEASE_VERSION=$RELEASE_TAG" >> $GITHUB_ENV
